name: extended_http_client
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  delayed_proxy_http_client: ^1.0.0
  ffi: '>=1.1.0 <3.0.0'
  fixnum: ^1.0.0
  pointycastle: ^3.0.1

dev_dependencies:
  ffigen: ^7.2.9
  lint: ^2.0.1
  test: ^1.21.0
